create database customers; 
use customers;
show tables;
select * from customer;  

# 01 What is the total revenu generated by male vs female customers?. 
select gender,  
sum(purchase_amount) as revenu 
from customer 
group by gender; 

# 02 Which customers used a discount but still spent more than the average purchase amount.
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and  purchase_amount >= (select avg(purchase_amount) from customer);

# 03 Which are the top 5 products with the highest average review rating. 
select item_purchased, round(avg(review_rating),2) as avg_pro_rating 
from customer 
group by item_purchased 
order by avg(review_rating) desc 
limit 5;

# 04 Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, avg(purchase_amount) 
from customer 
where shipping_type in ('standard','Express') 
group by shipping_type;

# 05 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers, 
round(avg(purchase_amount),2) as avg_spent,
round(sum(purchase_amount),2) as total_revenue 
from customer 
group by subscription_status 
order by total_revenue, avg_spent desc;

# Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
round(sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) * 100,2) as discount_rate
from customer
group by item_purchased 
order by discount_rate desc 
limit 5;

# 07 Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with customer_type as ( 
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning' 
    else 'Loyal' 
    end as customer_segment 
from customer 
) 

select customer_segment, count(*) as 'number_of _customers' 
from customer_type 
group by customer_segment;

# 08 What are the top 3 most purchased products within each category? 
with item_count as ( 
select category,
item_purchased, 
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank 
from customer 
group by category, item_purchased
) 

select item_rank, category, item_purchased, total_orders 
from item_count
where item_rank <=3; 

# 09 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select 
subscription_status,
count(customer_id) as repeat_buyer
from customer 
where previous_purchases > 5
group by subscription_status;

# 10 What is the revenue contribution of each age group?
select age_group,sum(purchase_amount)as total_revenue 
from customer 
group by age_group 
order by total_revenue desc;